# Site settings
title: cmos
email: christianmoscardi@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Christian Moscardi's personal website and blog.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.christianmoscardi.com" # the base hostname & protocol for your site
twitter_username: c_moscardi
github_username:  cmoscardi

# Build settings
markdown: kramdown
